# Hi, this is a release code changer to change code when you released a new version.
# This changes the README.md and pom.xml at the moment.
# Mabe i will add here more features or change them.
# Configuration

# What plugin version should be in the pom.xml
pom.release: 2.4.20-SNAPSHOT

# What version should be shown in the README.md latest badge
release.version: 2.4.11
