blank_issues_enabled: false
contact_links:
  - name: WorldSystem Discord
    url: https://discord.gg/cmdPMJ8
    about: Our Discord, you can try to ask questions here
  - name: WorldSystem Wiki
    url: https://github.com/Argantiu/WorldSystem-Updated/wiki
    about: Take a look at the wiki page for instructions how to setup and use WorldSystem