# This is a basic workflow to help you get started with Actions

name: Release code changer

on:
  push:
    branches: [ "master" ]

jobs:
  changeversion:
    runs-on: ubuntu-latest

    steps:
      - name: Get github directory
        id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.github
          key: ${{ runner.os }}-github

      - uses: actions/checkout@v3

      - name: Run the Version changer
        run: |
          chmod +x release-code-changer.sh
          ./release-code-changer.sh
